CREATE TABLE `dmsdb`.`buildingamenities`(  
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `BuildingId` INT(11),
  `AmenityId` INT(11),
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `UpdatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`)
);
