CREATE TABLE `lead` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Email` VARCHAR(50) NULL DEFAULT NULL,
	`Number` VARCHAR(50) NULL DEFAULT NULL,
	`Message` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
